language: python
python: 2.7
env:
  matrix:
  - TOXENV=py27
  - TOXENV=pypy
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist
  user: ChristophSchabert
  password:
    secure: iOn6jdOTkvhszGUp/Py9Ov17EUSnQaiASuXWiEHRUmo55nvHC62qz66o46PyMuU5JOSq4YeMQRugLD/dJyJfZ+vRt4JOy7iAdPLS2iJSI0X/vQSiCYQ0L96Fdaz8I4Kg17IIyKFSH7oiPkxSv9UuK0gQET1POZwHI0DOhCkSEiQEQ5HJj8enaQ4uUYWyGSTT3d7Pzc227RhKAvE4x9RbWtsRt6KBzbn7KqBIqw2UeAURAmbukSxbGdqb8x7F/a3FaY/88Tnb1fwmBXM8/Z84vcwBivpnxtluV7wdtSGTWC5BMgu2RR2FnBRwFTvxjpsfH5DryI8VIyrVHZIHUs7x+WaC04wk7PCIkFBw6XxDDcUCMwPTBvwXuafuva8UMjHjOhRIs0iyU5d8oQ/wc0Hlz2qjG9hzPg+RTdC+KILq5k0B3SVSn4ZR4VY17ye+dVFrsQA56oGrH5vzhkFr/6ps5SDU82QDK6BzZ2ZlGoinTesizXqOU7yeVAvO8RUB9ihGlvF64ykuOLpnod8dXDqgcsRiMqUrf75N/me6wHuJOBJ3cCBaZJunx2m46yMO0gs2Sd3DHnSsv67Nd7sK32qJkZwIyrSK7fBNW/NzA/ZmbfTznxT29GpkReK7zJF4LbN99gTVv6l2Vz2nPf8Mwj+Ado/J/oxW9Pv2NmHIY2HJlU8=
  on:
    tags: true
    repo: Christoph-Schabert/lambda_utils
    condition: "$TOXENV == py27"
