language: python
python: 3.5
env:
  matrix:
  - TOXENV=py35
  - TOXENV=py27
  - TOXENV=pypy
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ChristophSchabert
  password:
    secure: D+mGCl3Ie1MKpNI2HWEv3PVQncejOLC5DF9o2Y8eozldWxFBepkuZvpPgW9crTIqW8doJHEnrddF8PBoasd6Ufa5Kgjkan3jf5802MAx0csrN5qlkxux1ckw0tXKNNizdFQQAt4a1/j0YaUzksJN/lZOc5rc59MIRfi/X6tkcOYyEPzavynxBSIMkUoYsNIvAJBhRPPlg9rbSCBXwZ8V/kglH3Kjvb6ZgX4Yb8GsuiGC2TzQflgUulxdFpRA6pK1v0p5NH7nuR2t5pwYLyoaYI1zPSAtacR15Qwzz6FlcozB8SQdDH/IRzCrHTdLOx0qeHCDLTUHxbs408c5Sl17NAs6WxZq72MxAS83kUUHNuxiuDLRS2uqgoVhiNnRDSZW0FggliCqk8lTeiTjlKYnNTkIg3ZzdgYDwto96sAUcQgzL89+pu7CrjkqpMz21Ws+SM7o7ha9tr3RN3PMtpmE9AZ/pMMt60zdF3Z7iqPDz35qsZyPUEGmt/xJyQUpwXXnZL6clVYV/qJsVIjFuBlhoGlESvuV8lcuiKrZEzGdpknWOHyYWb7zJ4JnA2oy96e1RRMNR+N904i4EDNWDlU/MG80/ZjD2HhyOppFYPVSwJ3bqug+fSLAYGcagkN17JH6Ns6NOuuQDRePzMfp2QtHGh9/15kyG03Okup1h3YmHZs=
  on:
    tags: true
    repo: Christoph-Schabert/lambda_utils
    condition: "$TOXENV == py27"
