language: python
python: 2.7
env:
  matrix:
  - TOXENV=py27
  - TOXENV=pypy
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist
  user: ChristophSchabert
  password:
    secure: hgOBF5S5Q61fwZakqvrJhKFQyluoJZdHeUObMfuJNZO3WFriuoieVRF+oFHHy7nW1Y4fiM74K/TZ/FKHjzfFB+K4KCIpmJ0nqjmGZZcrJlELhcSag1iFtVMQqMHXhBd2/cMB6fhlvNUM5f3YDmqIC5CiBpm74muAX3hjBmwyiXjV/WCMqW19XEs2CQTZCdAgGL+LQU0pr3qNGYb8e+G+gtrZn2asMdqUNP17E339eWheHzaA/tKom3Mxq43FkOI5Y5JyM3+1Mc3CCzsP+q+CIFmPR9S6A0n32+mlDZyQWxL0OSlzga4SRq0REq1UiAyt9Udu5AgtyYf6/UQPsNT2NWHTY5Gp/Hxm67G803TTWOGO+cUMhteoIQlKnR9v7bzZ7jmRg8ln5L97A+tzAg1vbv3YPHxGt7KzL6UIAArxqvo/wUQANoC8P6e2CQJMMDbvTkhw8i2VbETc+kO9q+/IUpKIW3rsArp3dyOVPnzKzQhHjDfvTtwScWXWLMwPN7Bdl4WNs8cabVtUAr0I5uT2rj8zog/X3uUoyYAAoMCfIUNoBsCSzZoYWxOVfujxrtadUEn96cWPP9suDaw+Dmx51GbcoY8RYbsZZAMJwee+tvBXcRcbArCTVSn89FPZJAEaBWMCyNM9BUZrgdV5CAuyzvjHoSnQKzOsrvrLyWEVjuk=
  on:
    tags: true
    repo: Christoph-Schabert/lambda_utils
    condition: "$TOXENV == py27"
